export const POST_CATEGORIES = ['exchange', 'gift', 'found']

export const PLANT_TYPES = [
    'Roses',
    'Cacti',
    'Palms',
    'Ferns',
    'Orchids',
    'Bamboo',
    'Violets',
    'Lilies',
    'Daisies',
    'Sunflowers',
    'Tulips',
    'Bonsais',
    'Fruit Trees',
    'Ivies',
    'Succulents',
    'Shade Plants',
    'Indoor Plants',
    'Aquatic Plants',
    'Medicinal Plants',
    'Herbs',
    'Ornamental Trees',
    'Climbing Plants',
    'Grass',
    'Air Plants',
    'Carnivorous Plants'
]

export const PLANT_TYPE_LOGOS = {
    Roses: "jpg",
    Cacti: "jpg",
    Palms: "jpg",
    Ferns: "jpg",
    Orchids: "jpg",
    Bamboo: "jpg",
    Violets: "jpg",
    Lilies: "jpg",
    Daisies: "jpg",
    Sunflowers: "jpg",
    Tulips: "jpg",
    Bonsais: "jpg",
    "Fruit Trees": "jpg",
    Ivies: "jpg",
    Succulents: "jpg",
    "Shade Plants": "jpg",
    "Indoor Plants": "jpg",
    "Aquatic Plants": "jpg",
    "Medicinal Plants": "jpg",
    Herbs: "jpg",
    "Ornamental Trees": "jpg",
    "Climbing Plants": "jpg",
    Grass: "jpg",
    "Air Plants": "jpg",
    "Carnivorous Plants": "jpg"
}

export const EQUIPMENT_CONDITION = ['new', 'like new', 'used', 'well-worn']

export const EQUIPMENT_TYPES = {
    PotsAndContainers: [
        "pot",
        "container",
        "plant stand",
    ],
    WateringEquipment: [
        "watering can",
        "spray bottle",
        "garden hose",
        "nozzle",
        "watering system",
    ],
    GardeningTools: [
        "pruning shears",
        "gloves",
        "trowel",
        "spade",
        "rake",
        "shovel",
        "plant clips",
        "garden twine",
    ],
    PlantCare: [
        "grow lights",
        "humidity tray",
        "misting bottle",
        "fertilizer",
        "compost bin",
        "mulch",
        "potting mix",
        "insecticidal soap",
        "neem oil",
        "fungicide",
        "pest control sprays",
    ],
    PropagationAndSupport: [
        "propagation station",
        "trellis",
        "stakes",
        "plant support",
        "seed tray",
    ],
    MonitoringTools: [
        "moisture meter",
        "pH meter",
        "temperature and humidity monitor",
        "plant labels",
    ],
    DecorativeAndMiscellaneous: [
        "pebbles",
        "decorative stones",
    ],
}

