export const POST_CATEGORIES = ['exchange', 'gift', 'found']

export const PLANT_TYPES = [
    'Roses',
    'Cacti',
    'Palms',
    'Ferns',
    'Orchids',
    'Bamboo',
    'Violets',
    'Lilies',
    'Daisies',
    'Sunflowers',
    'Tulips',
    'Bonsais',
    'Fruit Trees',
    'Ivies',
    'Succulents',
    'Shade Plants',
    'Indoor Plants',
    'Aquatic Plants',
    'Medicinal Plants',
    'Herbs',
    'Ornamental Trees',
    'Climbing Plants',
    'Grass',
    'Air Plants',
    'Carnivorous Plants'
]

export const PLANT_TYPE_LOGOS = {
    Roses: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524956/IMG_6757_cwteo1.png",
    Cacti: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524955/IMG_6756-1_msjsqe.png",
    Palms: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524954/IMG_6754-1_ak2lpj.png",
    Ferns: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524952/IMG_6751-1utt_zxn7lt.png",
    Orchids: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524953/IMG_6752-1_pjo1wm.png",
    Bamboo: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524951/IMG_6749-1hh_tke4sw.png",
    Violets: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524950/IMG_6745-1_kjrzca.png",
    Lilies: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524949/IMG_6743-1_uqmawx.png",
    Daisies: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524948/IMG_6742-1_ewc7ni.png",
    Sunflowers: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524948/IMG_6741-1_i34zpl.png",
    Tulips: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524947/IMG_6738-1_xg48zn.png",
    Bonsais: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524945/IMG_6735-1_jo5p6d.png",
    "Fruit Trees": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524944/IMG_6734-1_nf2d1d.png",
    Ivies: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524943/IMG_6733-1_2_nhbyuj.png",
    Succulents: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524942/IMG_6732-1ggb_i7lqz7.png",
    "Shade Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524957/IMG_6845_zom3gn.png",
    "Indoor Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524933/Ee_mind3i.png",
    "Aquatic Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524940/IMG_6728-1_uquhf6.png",
    "Medicinal Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524938/IMG_6709-1hth_ebi32d.png",
    Herbs: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524936/IMG_6709-1e_mnnxk3.png",
    "Ornamental Trees": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524935/IMG_6709-1_djtozj.png",
    "Climbing Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524932/ClimbingPlants_jcc0un.png",
    Grass: "https://res.cloudinary.com/depxadgb3/image/upload/v1705524935/Grass_ltusql.png",
    "Air Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524930/AirPlants_dqjaw1.png",
    "Carnivorous Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1705524931/CarnivorousPlanta_a9c86p.png"
}

export const EQUIPMENT_CONDITION = ['new', 'like new', 'used', 'well-worn']

export const EQUIPMENT_TYPES = {
    PotsAndContainers: [
        "pot",
        "container",
        "plant stand",
    ],
    WateringEquipment: [
        "watering can",
        "spray bottle",
        "garden hose",
        "nozzle",
        "watering system",
    ],
    GardeningTools: [
        "pruning shears",
        "gloves",
        "trowel",
        "spade",
        "rake",
        "shovel",
        "plant clips",
        "garden twine",
    ],
    PlantCare: [
        "grow lights",
        "humidity tray",
        "misting bottle",
        "fertilizer",
        "compost bin",
        "mulch",
        "potting mix",
        "insecticidal soap",
        "neem oil",
        "fungicide",
        "pest control sprays",
    ],
    PropagationAndSupport: [
        "propagation station",
        "trellis",
        "stakes",
        "plant support",
        "seed tray",
    ],
    MonitoringTools: [
        "moisture meter",
        "pH meter",
        "temperature and humidity monitor",
        "plant labels",
    ],
    DecorativeAndMiscellaneous: [
        "pebbles",
        "decorative stones",
    ],
}

