export const POST_CATEGORIES = ['exchange', 'gift', 'found']

export const PLANT_TYPES = [
    'Roses',
    'Cacti',
    'Palms',
    'Ferns',
    'Orchids',
    'Bamboo',
    'Violets',
    'Lilies',
    'Daisies',
    'Sunflowers',
    'Tulips',
    'Bonsais',
    'Fruit Trees',
    'Ivies',
    'Succulents',
    'Shade Plants',
    'Indoor Plants',
    'Aquatic Plants',
    'Medicinal Plants',
    'Herbs',
    'Ornamental Trees',
    'Climbing Plants',
    'Grass',
    'Air Plants',
    'Carnivorous Plants'
]

export const PLANT_TYPE_LOGOS = {
    Roses: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202370/IMG_6757_utsmab.png",
    Cacti: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202370/IMG_6756-1_uysyiw.png",
    Palms: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6754-1_vleblq.png",
    Ferns: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202373/IMG_6730e_eenw2f.png",
    Orchids: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6752-1_gudajg.png",
    Bamboo: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6749-1hh_kgt6vo.png",
    Violets: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6745-1_bxzlsf.png",
    Lilies: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6743-1_ecpkei.png",
    Daisies: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202368/IMG_6742-1_r7atyr.png",
    Sunflowers: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202369/IMG_6741-1_x4ylzs.png",
    Tulips: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202368/IMG_6738-1_dyqq4v.png",
    Bonsais: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202368/IMG_6735-1_f73sxl.png",
    "Fruit Trees": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202368/IMG_6737-1_rvodym.png",
    Ivies: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202374/Foggy_y44l8a.png",
    Succulents: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202373/IMG_6732-1ggb_b4rwb2.png",
    "Shade Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1704996057/IMG_6845_cg08pk.png",
    "Indoor Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202374/Ee_gfctcx.png",
    "Aquatic Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202372/IMG_6728-1_siwfaq.png",
    "Medicinal Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202372/IMG_6709-1hth_np8kdv.png",
    Herbs: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202371/IMG_6709-1e_v5jddc.png",
    "Ornamental Trees": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202371/IMG_6709-1_w0xrqy.png",
    "Climbing Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202374/ClimbingPlants_lfpgvc.png",
    Grass: "https://res.cloudinary.com/depxadgb3/image/upload/v1703202370/Grass_ygmmyl.png",
    "Air Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202374/AirPlants_javsfj.png",
    "Carnivorous Plants": "https://res.cloudinary.com/depxadgb3/image/upload/v1703202374/CarnivorousPlanta_umhpvw.png"
}

export const EQUIPMENT_CONDITION = ['new', 'like new', 'used', 'well-worn']

export const EQUIPMENT_TYPES = {
    PotsAndContainers: [
        "pot",
        "container",
        "plant stand",
    ],
    WateringEquipment: [
        "watering can",
        "spray bottle",
        "garden hose",
        "nozzle",
        "watering system",
    ],
    GardeningTools: [
        "pruning shears",
        "gloves",
        "trowel",
        "spade",
        "rake",
        "shovel",
        "plant clips",
        "garden twine",
    ],
    PlantCare: [
        "grow lights",
        "humidity tray",
        "misting bottle",
        "fertilizer",
        "compost bin",
        "mulch",
        "potting mix",
        "insecticidal soap",
        "neem oil",
        "fungicide",
        "pest control sprays",
    ],
    PropagationAndSupport: [
        "propagation station",
        "trellis",
        "stakes",
        "plant support",
        "seed tray",
    ],
    MonitoringTools: [
        "moisture meter",
        "pH meter",
        "temperature and humidity monitor",
        "plant labels",
    ],
    DecorativeAndMiscellaneous: [
        "pebbles",
        "decorative stones",
    ],
}

